//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendSMSForMC.CardworksWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:webservices.com.my", ConfigurationName="CardworksWS.Cardworks")]
    public interface Cardworks {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cardReloadReturn")]
        SendSMSForMC.CardworksWS.CardReloadRespBean cardReload(SendSMSForMC.CardworksWS.CardReloadReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rewardAdjustmentReturn")]
        SendSMSForMC.CardworksWS.RedeemRewardRespBean rewardAdjustment(SendSMSForMC.CardworksWS.RedeemRewardReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="hostSignOnReturn")]
        SendSMSForMC.CardworksWS.HostSignOnRespBean hostSignOn(SendSMSForMC.CardworksWS.HostSignOnReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="rewardEnquiryReturn")]
        SendSMSForMC.CardworksWS.RewardEnquiryRespBean rewardEnquiry(SendSMSForMC.CardworksWS.RewardEnquiryReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cardProfileMaintenanceReturn")]
        SendSMSForMC.CardworksWS.CardProfileMaintRespBean cardProfileMaintenance(SendSMSForMC.CardworksWS.CardProfileMaintReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cardAdjustmentReturn")]
        SendSMSForMC.CardworksWS.CardAdjustmentRespBean cardAdjustment(SendSMSForMC.CardworksWS.CardAdjustmentReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="directDebitReturn")]
        SendSMSForMC.CardworksWS.DirectDebitRespBean directDebit(SendSMSForMC.CardworksWS.DirectDebitReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PINSelectionReturn")]
        SendSMSForMC.CardworksWS.PINSelectionRespBean PINSelection(SendSMSForMC.CardworksWS.PINSelectionReqBean in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPntItems))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RewardEnquiryPanItems))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="limitMngmtReturn")]
        SendSMSForMC.CardworksWS.LimitMngmtRespBean limitMngmt(SendSMSForMC.CardworksWS.LimitMngmtReqBean in0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardReloadReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string branchCodeField;
        
        private string currencyCodeField;
        
        private string expiryDateField;
        
        private string fiField;
        
        private string panField;
        
        private string referenceNoField;
        
        private string reloadMethodField;
        
        private string reloadSourceField;
        
        private string sequenceNoField;
        
        private string sourceSystemField;
        
        private string srcField;
        
        private string surchargeFeeField;
        
        private string surchargeFeeSignField;
        
        private string transferorPANField;
        
        private string actIndField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string reloadMethod {
            get {
                return this.reloadMethodField;
            }
            set {
                this.reloadMethodField = value;
                this.RaisePropertyChanged("reloadMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string reloadSource {
            get {
                return this.reloadSourceField;
            }
            set {
                this.reloadSourceField = value;
                this.RaisePropertyChanged("reloadSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
                this.RaisePropertyChanged("sourceSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
                this.RaisePropertyChanged("src");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string surchargeFee {
            get {
                return this.surchargeFeeField;
            }
            set {
                this.surchargeFeeField = value;
                this.RaisePropertyChanged("surchargeFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string surchargeFeeSign {
            get {
                return this.surchargeFeeSignField;
            }
            set {
                this.surchargeFeeSignField = value;
                this.RaisePropertyChanged("surchargeFeeSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transferorPAN {
            get {
                return this.transferorPANField;
            }
            set {
                this.transferorPANField = value;
                this.RaisePropertyChanged("transferorPAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class LimitMngmtRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class LimitMngmtReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionField;
        
        private string fiField;
        
        private string actIndField;
        
        private string panField;
        
        private string holdAmtField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        public string holdAmt {
            get {
                return this.holdAmtField;
            }
            set {
                this.holdAmtField = value;
                this.RaisePropertyChanged("holdAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class PINSelectionRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class PINSelectionReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fiField;
        
        private string actIndField;
        
        private string panField;
        
        private string mobileNoField;
        
        private string newPINField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("mobileNo");
            }
        }
        
        /// <remarks/>
        public string newPIN {
            get {
                return this.newPINField;
            }
            set {
                this.newPINField = value;
                this.RaisePropertyChanged("newPIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class DirectDebitRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string approvalCodeField;
        
        private string referenceNoField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string approvalCode {
            get {
                return this.approvalCodeField;
            }
            set {
                this.approvalCodeField = value;
                this.RaisePropertyChanged("approvalCode");
            }
        }
        
        /// <remarks/>
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class DirectDebitReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string currencyCodeField;
        
        private string cvv2Field;
        
        private string expiryDateField;
        
        private string fiField;
        
        private string midField;
        
        private string panField;
        
        private string referenceNoField;
        
        private string sequenceNoField;
        
        private string tidField;
        
        private string trxDateField;
        
        private string trxTimeField;
        
        private string actIndField;
        
        private string merNameField;
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cvv2 {
            get {
                return this.cvv2Field;
            }
            set {
                this.cvv2Field = value;
                this.RaisePropertyChanged("cvv2");
            }
        }
        
        /// <remarks/>
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        public string mid {
            get {
                return this.midField;
            }
            set {
                this.midField = value;
                this.RaisePropertyChanged("mid");
            }
        }
        
        /// <remarks/>
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        public string trxDate {
            get {
                return this.trxDateField;
            }
            set {
                this.trxDateField = value;
                this.RaisePropertyChanged("trxDate");
            }
        }
        
        /// <remarks/>
        public string trxTime {
            get {
                return this.trxTimeField;
            }
            set {
                this.trxTimeField = value;
                this.RaisePropertyChanged("trxTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merName {
            get {
                return this.merNameField;
            }
            set {
                this.merNameField = value;
                this.RaisePropertyChanged("merName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardAdjustmentRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardAdjustmentReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actIndField;
        
        private string adjCdeField;
        
        private string fiField;
        
        private string panField;
        
        private string sequenceNoField;
        
        private string adjAmtField;
        
        private string brchCdeField;
        
        private string merchantIdField;
        
        private string termIdField;
        
        private string officerIdField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string adjCde {
            get {
                return this.adjCdeField;
            }
            set {
                this.adjCdeField = value;
                this.RaisePropertyChanged("adjCde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string adjAmt {
            get {
                return this.adjAmtField;
            }
            set {
                this.adjAmtField = value;
                this.RaisePropertyChanged("adjAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string brchCde {
            get {
                return this.brchCdeField;
            }
            set {
                this.brchCdeField = value;
                this.RaisePropertyChanged("brchCde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string termId {
            get {
                return this.termIdField;
            }
            set {
                this.termIdField = value;
                this.RaisePropertyChanged("termId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string officerId {
            get {
                return this.officerIdField;
            }
            set {
                this.officerIdField = value;
                this.RaisePropertyChanged("officerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("remarks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardProfileMaintRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardProfileMaintReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actIndField;
        
        private string actCdeField;
        
        private string actTypeField;
        
        private string fiField;
        
        private string panField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actCde {
            get {
                return this.actCdeField;
            }
            set {
                this.actCdeField = value;
                this.RaisePropertyChanged("actCde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actType {
            get {
                return this.actTypeField;
            }
            set {
                this.actTypeField = value;
                this.RaisePropertyChanged("actType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RewardEnquiryPntItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string expiryMonthField;
        
        private string pointGoingExpiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string expiryMonth {
            get {
                return this.expiryMonthField;
            }
            set {
                this.expiryMonthField = value;
                this.RaisePropertyChanged("expiryMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointGoingExpired {
            get {
                return this.pointGoingExpiredField;
            }
            set {
                this.pointGoingExpiredField = value;
                this.RaisePropertyChanged("pointGoingExpired");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RewardEnquiryPanItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bonusPointOfTheMonthField;
        
        private string panField;
        
        private string pointAdjustmentField;
        
        private string pointAvailableField;
        
        private string pointCarriedForwardField;
        
        private string pointEarnThisMonthField;
        
        private string pointRedeemedField;
        
        private RewardEnquiryPntItems[] rewardEnquiryPntItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bonusPointOfTheMonth {
            get {
                return this.bonusPointOfTheMonthField;
            }
            set {
                this.bonusPointOfTheMonthField = value;
                this.RaisePropertyChanged("bonusPointOfTheMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointAdjustment {
            get {
                return this.pointAdjustmentField;
            }
            set {
                this.pointAdjustmentField = value;
                this.RaisePropertyChanged("pointAdjustment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointAvailable {
            get {
                return this.pointAvailableField;
            }
            set {
                this.pointAvailableField = value;
                this.RaisePropertyChanged("pointAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointCarriedForward {
            get {
                return this.pointCarriedForwardField;
            }
            set {
                this.pointCarriedForwardField = value;
                this.RaisePropertyChanged("pointCarriedForward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointEarnThisMonth {
            get {
                return this.pointEarnThisMonthField;
            }
            set {
                this.pointEarnThisMonthField = value;
                this.RaisePropertyChanged("pointEarnThisMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointRedeemed {
            get {
                return this.pointRedeemedField;
            }
            set {
                this.pointRedeemedField = value;
                this.RaisePropertyChanged("pointRedeemed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RewardEnquiryPntItems[] rewardEnquiryPntItems {
            get {
                return this.rewardEnquiryPntItemsField;
            }
            set {
                this.rewardEnquiryPntItemsField = value;
                this.RaisePropertyChanged("rewardEnquiryPntItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RewardEnquiryRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string crnField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private RewardEnquiryPanItems[] rewardEnquiryPanItemsField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string crn {
            get {
                return this.crnField;
            }
            set {
                this.crnField = value;
                this.RaisePropertyChanged("crn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RewardEnquiryPanItems[] rewardEnquiryPanItems {
            get {
                return this.rewardEnquiryPanItemsField;
            }
            set {
                this.rewardEnquiryPanItemsField = value;
                this.RaisePropertyChanged("rewardEnquiryPanItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RewardEnquiryReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string crnField;
        
        private string fiField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string crn {
            get {
                return this.crnField;
            }
            set {
                this.crnField = value;
                this.RaisePropertyChanged("crn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class HostSignOnRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class HostSignOnReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fiField;
        
        private string passwordField;
        
        private string sequenceNoField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RedeemRewardRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string crnField;
        
        private string pointAdjustmentField;
        
        private string pointAvailableField;
        
        private string pointCarriedForwardField;
        
        private string pointEarnThisMonthField;
        
        private string pointRedeemedField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        private string panField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string crn {
            get {
                return this.crnField;
            }
            set {
                this.crnField = value;
                this.RaisePropertyChanged("crn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointAdjustment {
            get {
                return this.pointAdjustmentField;
            }
            set {
                this.pointAdjustmentField = value;
                this.RaisePropertyChanged("pointAdjustment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointAvailable {
            get {
                return this.pointAvailableField;
            }
            set {
                this.pointAvailableField = value;
                this.RaisePropertyChanged("pointAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointCarriedForward {
            get {
                return this.pointCarriedForwardField;
            }
            set {
                this.pointCarriedForwardField = value;
                this.RaisePropertyChanged("pointCarriedForward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointEarnThisMonth {
            get {
                return this.pointEarnThisMonthField;
            }
            set {
                this.pointEarnThisMonthField = value;
                this.RaisePropertyChanged("pointEarnThisMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pointRedeemed {
            get {
                return this.pointRedeemedField;
            }
            set {
                this.pointRedeemedField = value;
                this.RaisePropertyChanged("pointRedeemed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class RedeemRewardReqBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string crnField;
        
        private string fiField;
        
        private string sequenceNoField;
        
        private string panField;
        
        private string actIndField;
        
        private string pointField;
        
        private string rewardActionField;
        
        private string txnDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string crn {
            get {
                return this.crnField;
            }
            set {
                this.crnField = value;
                this.RaisePropertyChanged("crn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
                this.RaisePropertyChanged("fi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string actInd {
            get {
                return this.actIndField;
            }
            set {
                this.actIndField = value;
                this.RaisePropertyChanged("actInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rewardAction {
            get {
                return this.rewardActionField;
            }
            set {
                this.rewardActionField = value;
                this.RaisePropertyChanged("rewardAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string txnDesc {
            get {
                return this.txnDescField;
            }
            set {
                this.txnDescField = value;
                this.RaisePropertyChanged("txnDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.webservices.com.my")]
    public partial class CardReloadRespBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string approvalCodeField;
        
        private string latestBalanceField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string sequenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string approvalCode {
            get {
                return this.approvalCodeField;
            }
            set {
                this.approvalCodeField = value;
                this.RaisePropertyChanged("approvalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string latestBalance {
            get {
                return this.latestBalanceField;
            }
            set {
                this.latestBalanceField = value;
                this.RaisePropertyChanged("latestBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("sequenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardworksChannel : SendSMSForMC.CardworksWS.Cardworks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardworksClient : System.ServiceModel.ClientBase<SendSMSForMC.CardworksWS.Cardworks>, SendSMSForMC.CardworksWS.Cardworks {
        
        public CardworksClient() {
        }
        
        public CardworksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardworksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardworksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardworksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SendSMSForMC.CardworksWS.CardReloadRespBean cardReload(SendSMSForMC.CardworksWS.CardReloadReqBean in0) {
            return base.Channel.cardReload(in0);
        }
        
        public SendSMSForMC.CardworksWS.RedeemRewardRespBean rewardAdjustment(SendSMSForMC.CardworksWS.RedeemRewardReqBean in0) {
            return base.Channel.rewardAdjustment(in0);
        }
        
        public SendSMSForMC.CardworksWS.HostSignOnRespBean hostSignOn(SendSMSForMC.CardworksWS.HostSignOnReqBean in0) {
            return base.Channel.hostSignOn(in0);
        }
        
        public SendSMSForMC.CardworksWS.RewardEnquiryRespBean rewardEnquiry(SendSMSForMC.CardworksWS.RewardEnquiryReqBean in0) {
            return base.Channel.rewardEnquiry(in0);
        }
        
        public SendSMSForMC.CardworksWS.CardProfileMaintRespBean cardProfileMaintenance(SendSMSForMC.CardworksWS.CardProfileMaintReqBean in0) {
            return base.Channel.cardProfileMaintenance(in0);
        }
        
        public SendSMSForMC.CardworksWS.CardAdjustmentRespBean cardAdjustment(SendSMSForMC.CardworksWS.CardAdjustmentReqBean in0) {
            return base.Channel.cardAdjustment(in0);
        }
        
        public SendSMSForMC.CardworksWS.DirectDebitRespBean directDebit(SendSMSForMC.CardworksWS.DirectDebitReqBean in0) {
            return base.Channel.directDebit(in0);
        }
        
        public SendSMSForMC.CardworksWS.PINSelectionRespBean PINSelection(SendSMSForMC.CardworksWS.PINSelectionReqBean in0) {
            return base.Channel.PINSelection(in0);
        }
        
        public SendSMSForMC.CardworksWS.LimitMngmtRespBean limitMngmt(SendSMSForMC.CardworksWS.LimitMngmtReqBean in0) {
            return base.Channel.limitMngmt(in0);
        }
    }
}
